### PR TITLE
Added as="" to the list of attributes for <link>

### PR DESCRIPTION
**Pull request by ialpert**

### CODE REVIEW

**Comment by ialpert** [comment]
Hey @lordgiotto  -- in one of my projects I tried to render code similar to 

```
  <link rel="preload" href="bg-image-narrow.png" as="image" media="(max-width: 600px)">
  <link rel="preload" href="bg-image-wide.png" as="image" media="(min-width: 601px)">
```
but got "as" is a required attribute for preload from Chrome. Not sure I did the right thing, but I whitelisted attribute and wrote a basic test to for it. 

I had to turn my prettier off (if you can supply your ruleset for the contributions that would be awesome) but tslint seems to be happy.

Please let me know if that is a proper feature to do.

For the reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by lordgiotto** [comment]
Hi @ialpert, thank you very much for bringing up this issue, I wasn't aware of this! :)

I think more changes are needed to solve this problem though (with this PR you are changing just the types, but the actual behaviour is not affected).
Let me explain how it works, and help me clarify if I correctly understood your need.

**How this library identifies which tags to update**
Given multiple tags definitions in multiple components, this library needs to understand which tags are actually new tags, and which ones are old tags that should be updated.
To achieve this, for each tag type (meta and links) a set of "queryable attributes" is internally defined, and two tags definitions are considered the same tag if all these attributes are the same.

For links, the "queryable attributes" are: `id` (this works for every tag type), `rel` and `sizes`.

So, for instance, if in one of your components you write:
```
useMetaTags({
  links: [
    { rel: 'icon', sizes: '72x72', ref: './icon.png' }
  ]
})
```
this will create `<link rel="icon" sizes="72x72" href="./icon.png" />`.
If then in another component you write:
```
useMetaTags({
  links: [
    { rel: 'icon', sizes: '72x72', ref: './icon2.png' }
  ]
})
```
the previous created tag will be updated `<link rel="icon" sizes="72x72" href="./icon2.png" />`.

On the other side, if in the first component you write:
```
useMetaTags({
  links: [
    { rel: 'icon', sizes: '72x72', ref: './icon.png' }
  ]
})
```
And in the other one you write:
```
useMetaTags({
  links: [
    { rel: 'icon', ref: './icon2.png' }
  ]
})
```
this will create two tags, because the "queryable attribute" are not the same (the first has defined sizes, the second one don't).
```
<link rel="icon" sizes="72x72" href="./icon.png" />
<link rel="icon" href="./icon2.png" />
```

**The case of rel=preload**
That said, you understand that, unfortunately, this is not going to work in your case.
Probably this logic should be revised, but I'm still not sure how to do that.
One thing I should do for sure is to add `media` to the "queryable attributes" for links, because it makes totally sense.
Still, this would not solve your issue, because you should be able to add as many rel=preload as you want, according to the docs.

I'm going to think about it, but in the meantime, as a workaround, you can just add the `id` attribute to the definition of the preload tags, like this:
```
useMetaTags({
  links: [
    { rel: 'preload', href: bg-image-narrow.png', media: '(max-width: 600px)', id: 'bg-image-narrow-preload' },
    { rel: 'preload', href: bg-image-wide.png', media: '(max-width: 601px)', id: 'bg-image-wide-preload' }
  ]
})
```

I know it's not ideal, but I promise I'll try to figure out a better solution :)

If you want to open an issue for this I would be extremely grateful, so I will copy there this comment and we can investigate further this problem :)

**Comment by ialpert** [comment]
@lordgiotto  thank you for getting back so quickly! You can totally disregard this PR as now I see that "as" is not an issue but rather hash calculation to update tag instead of creating a new one. 

I took a quick look at parse.ts and my immediate reaction was to try to add "href" to query keys :)  however tests prove me wrong. 

ID solution is totally acceptable, thank you for that one

**Comment by lordgiotto** [comment]
Thanks @ialpert, I'm going to close this PR.
Anyway, I will add the prettier config to the repository as you pointed out, and I will try to improve the documentation about the "queryable attributes" logic (it's a bit tricky and probably not easy to understand).
Let me know if you have any other problem :)

Cheers!

**Pull request closed without merging**
